### ISSUE TITLE
Add size of resultset to top of results table

### ISSUE THREAD

**Issue by ryscher** [InfoCommons/cic#163]
(similar to existing site)

**Comment by sg3847** [comment]
@ryscher The existing site by default shows "Search results for **covid** found the following **1883** results.". I'm guessing this is because it's getting the result set using "covid" keyword behind the scenes from a larger set. Since we are not doing a default search using "covid" keyword, we can't have the same message. How do you want to handle it? Some options are:

1. We can change the message to be "Showing **1883** results" (and not show the keyword at all). 
2. Show the message ""Search results for **""** found the following **1883** results." (as you type the keyword, "" changes to the keyword)
3. Switch between 2 separate messages. a) A default message when there's no keyword (same message as 1 above) and, b) Existing CIC message (as in 2 above) when keyword exists.

**Comment by ryscher** [comment]
Option 1 is good.
